apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rfc6035-2otel.fullname" . }}
  labels:
    {{- include "rfc6035-2otel.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "rfc6035-2otel.config" . | nindent 4 }}
