apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfc6035-2otel.fullname" . }}
  labels:
    {{- include "rfc6035-2otel.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: sip-publish
      port: {{ .Values.service.port }}
      targetPort: sip-publish
      protocol: UDP
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "rfc6035-2otel.selectorLabels" . | nindent 4 }}
