name: actionlint
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
permissions: {}
jobs:
  actionlint:
    permissions:
      contents: read
    uses: rknightion/.github/.github/workflows/actionlint.yml@65aedb61754e9bf31e947c17409256ba0c58c637 # v1.4.3
